title: Calculadoras
collections:
  calculators:
    permalink: /:name
    output: true

manifest_name: Calculadoras
manifest_short_name: Calculadoras
manifest_lang: es
manifest_display: standalone
manifest_background_color: white
manifest_theme_color: "#343A40"
